Add checking for incoming data age
pytroll/trollflow2 pull request #151
Opened 2022-06-03 08:34 UTC by pnuu

With this PR it is possible to discard "too old" data before it is processed.

My use-case is the occasional data outages in Eumetacast, where the data are often sent late to make the data series intact. This causes the processing queue to stay full for hours (depending on the outage duration), and delays the processing of current data. With this feature it would be possible to discard the old data.

 - [x] Tests added  
 - [ ] Tests passed 
 - [x] Passes ``flake8 trollflow2`` 
 - [x] Fully documented

2022-06-03 08:44 UTC, mraspaud commented
Maybe a stupid question, but should this not be done earlier in the chain? like trollmoves or segment gatherer?

2022-06-03 09:54 UTC, pnuu commented
I was thinking about that. And if I made it so that there'd be option to process _only_ old ones, we could use the same collectors and have a "history processor" as a separate Trollflow2 entity, but still have only one collector. I think this is definitely the correct place for the filtering.

2022-06-03 11:56 UTC, pnuu commented
This now does what I was thinking about, the logic might not be that clear. Even I got my brains in a knot defining the tests...

2022-07-19 09:22 UTC, mraspaud requested changes
Looks good, just a couple of suggestions.

2022-07-19 09:24 UTC, mraspaud commented
This is an interesting problem. At the moment we don't have a priority system for the data, but if we had we could lower it for old data. That would allow for old data to be processed during the idle times...
Having a priority system is something I thought of when seeing how we could use trollflow2 in combination with dask distributed. One instance of trollflow2 would handle all different data types... but yeah, nothing we need to implement now :)

2022-09-02 10:20 UTC, pnuu commented on doc/source/index.rst
> +data newer than than the defined time.
```suggestion
data newer than the defined time.
```

2022-09-02 13:55 UTC, mraspaud approved these changes
LGTM

2022-09-02 14:09 UTC, merged